/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cashmaker_android_Shell_Key */

#ifndef _Included_com_cashmaker_android_Shell_Key
#define _Included_com_cashmaker_android_Shell_Key
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
