/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cashmaker_android_act_InjectActivity */

#ifndef _Included_com_cashmaker_android_act_InjectActivity
#define _Included_com_cashmaker_android_act_InjectActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cashmaker_android_act_InjectActivity
 * Method:    changeMethod
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_cashmaker_android_act_InjectActivity_changeMethod
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
